b_1 = input('Please enter building height No. 1: ') # b - building
if b_1.isdigit() != True:
  b_1 = input('Please enter an integer: ')
  if b_1.isdigit() != True:
    b_1 = 0
b_2 = input('Please enter building height No. 2: ')
if b_2.isdigit() != True:
  b_2 = input('Please enter an integer: ')
  if b_2.isdigit() != True:
    b_2 = 0
b_3 = input('Please enter building height No. 3: ')
if b_3.isdigit() != True:
  b_3 = input('Please enter an integer: ')
  if b_3.isdigit() != True:
    b_3 = 0
b_4 = input('Please enter building height No. 4: ')
if b_4.isdigit() != True:
  b_4 = input('Please enter an integer: ')
  if b_4.isdigit() != True:
    b_4 = 0
b_5 = input('Please enter building height No. 5: ')
if b_5.isdigit() != True:
  b_5 = input('Please enter an integer: ')
  if b_5.isdigit() != True:
    b_5 = 0
b_6 = input('Please enter building height No. 6: ')
if b_6.isdigit() != True:
  b_6 = input('Please enter an integer: ')
  if b_6.isdigit() != True:
    b_6 = 0
b_7 = input('Please enter building height No. 7: ')
if b_7.isdigit() != True:
  b_7 = input('Please enter an integer: ')
  if b_7.isdigit() != True:
    b_7 = 0
b_8 = input('Please enter building height No. 8: ')
if b_8.isdigit() != True:
  b_8 = input('Please enter an integer: ')
  if b_8.isdigit() != True:
    b_8 = 0
b_9 = input('Please enter building height No. 9: ')
if b_9.isdigit() != True:
  b_9 = input('Please enter an integer: ')
  if b_9.isdigit() != True:
    b_9 = 0
b_10 = input('Please enter building height No. 10: ')
if b_10.isdigit() != True:
  b_10 = input('Please enter an integer: ')
  if b_10.isdigit() != True:
    b_10 = 0
b_1 = int(b_1)
b_2 = int(b_2)
b_3 = int(b_3)
b_4 = int(b_4)
b_5 = int(b_5)
b_6 = int(b_6)
b_7 = int(b_7)
b_8 = int(b_8)
b_9 = int(b_9)
b_10 = int(b_10)
list = [b_1, b_2, b_3, b_4, b_5, b_6, b_7, b_8, b_9, b_10]
list.sort()
print('The tallest buildings: ', list[-1:-2:-1], 'm.,', list[-2:-3:-1],'m.,', list[-3:-4:-1], 'm.')
